### ISSUE TITLE
docker-compose validation doesn't take into account .env files

### ISSUE THREAD

**Issue by tpage-alfresco** [IamTheFij/docker-pre-commit#10]
We have the following directory structure:
```
.pre-commit-config.yaml
directory/
+-- .env
+-- docker-compose.yml
```

Our docker-compose.yml file contains port definitions like:
```
    ports:
      - "${POSTGRES_PORT}:5432"
```

The validation doesn't take the `.env` file into account and so replaces the token with an empty string. This then causes the pre-commit check to fail with
```
The Compose file './directory/docker-compose.yml' is invalid because:
services.postgres.ports is invalid: Port ranges don't match in length
```

**Comment by tpage-alfresco** [comment]
Locally we have fixed this by copying the script and editing it to include the `.env` file:
```
check_file() {
    local file=$1
    local dir=$(dirname $file)
    local env_instruction=""
    if [[ -f "$dir/.env" ]]; then
        env_instruction="--env-file $dir/.env"
    fi
    env $COMPOSE --file "$file" $env_instruction config --quiet 2>&1 \
        | sed "/variable is not set. Defaulting/d"
    return "${PIPESTATUS[0]}"
}
```

**Comment by ViViDboarder** [comment]
You should be able to also fix this using syntax to set a default value.

In my experience, the primary vale odd the `.env` file is to not have it committed in the repo. Pre-commit is often run on different machines and in CI where you wouldn’t be guaranteed to have the same `.env` file.

**Comment by tpage-alfresco** [comment]
> You should be able to also fix this using sax to set a default value

I'm not sure what "sax" is. Where should I search for it?

> In my experience, the primary vale odd the .env file is to not have it committed in the repo.

For repos which don't contain the `.env` file then I'm not sure there's a good solution to this bug.

**Comment by ViViDboarder** [comment]
Woops. Syntax is what I meant. Eg. `${VAR:-default}`
