### ISSUE TITLE
--no-verify

### ISSUE THREAD

**Issue by dolfinus** [IamTheFij/docker-pre-commit#2]
Hi.

I've installed `docker-compose-check` pre-commit hook into my repo and checked all files.

During the check this error was returned:
```
Validate docker-compose files............................................Failed
- hook id: docker-compose-check
- duration: 1.52s
- exit code: 1

Couldn't find env file: my_repo/.env
ERROR: docker-compose.yml
To ignore, use --no-verify
```

My docker-compose.yml:
```yml
version: '3.5'
services:
  scorer:
    image: my/image
    env_file: .env
    ...
```
`.env` file does not exist in the repo dir, so that's why `docker-compose config` returns error:
```
> docker-compose -f docker-compose.yml config 
ERROR: Couldn't find env file: my_repo/.env
```

But the message `To ignore, use --no-verify` is completely unuseful:
1. There is no handler for `--no-verify` option in the shell script:
https://github.com/IamTheFij/docker-pre-commit/blob/aeda358a4a1a064958fd994c9209047bd8c783c8/compose-check.sh#L27
2. `docker-compose config` command does not have such an option too:
```
> docker-compose config -h
Validate and view the Compose file.

Usage: config [options]

Options:
    --resolve-image-digests  Pin image tags to digests.
    --no-interpolate         Don't interpolate environment variables.
    -q, --quiet              Only validate the configuration, don't print
                             anything.
    --services               Print the service names, one per line.
    --volumes                Print the volume names, one per line.
    --hash="*"               Print the service config hash, one per line.
                             Set "service1,service2" for a list of specified services
                             or use the wildcard symbol to display all services.
```

IMHO, this warning should be removed.

**Comment by IamTheFij** [comment]
`--no-verify` is for `git commit` to bypass the hooks.

**Comment by dolfinus** [comment]
So you recommend to completely ignore all pre-commits hooks installed for a repo just because one step is failing? That's not sound good.

**Comment by IamTheFij** [comment]
Fair enough. I wouldn't personally recommend that. I'll change the notice.

**Comment by dolfinus** [comment]
Thanks!
