### ISSUE TITLE
Hadolint hook can be removed

### ISSUE THREAD

**Issue by wwuck** [IamTheFij/docker-pre-commit#3]
The hadolint hook here can be removed as there is now a pre-commit hook in the official hadolint repository at https://github.com/hadolint/hadolint/blob/master/.pre-commit-hooks.yaml

**Comment by IamTheFij** [comment]
Thanks! I probably should have sent them a patch back when I added it here too. Oh well. It looks like they added both the Docker and non-Docker versions much like I did, so it should be save to remove and replace.

As to not break workflow for people, I'll try to do this gradually by adding a warning first.
