### ISSUE TITLE
Executable `hadolint` not found

### ISSUE THREAD

**Issue by gitkent** [IamTheFij/docker-pre-commit#4]
Hi guys, 

I am using VS Code for my IDE and I have hadolint-system setup as pre-commit hooks. When I am committing from my IDE, I get the following error:

```
... ...
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
Lint Dockerfiles.........................................................Failed
- hook id: hadolint-system
- exit code: 1

Executable `hadolint` not found
```

However, when I am doing it from command line, pre-commit is passing without issue:
```
❯ pre-commit run -a
Lint Dockerfiles.........................................................Passed
```

and this is my executable `hadolint`
```
❯ which hadolint
/usr/local/bin/hadolint
```

Anyone has the similar issue before?

**Comment by IamTheFij** [comment]
This likely has to do with your `$PATH` variable. The shell that VSCode is running in must not include that path.
